import type { Instance, Receiver, BankAccount, BlockchainWallet, ApiKey } from '../types'
import { MOCK_INSTANCE_ID } from '../utils/constants'

const now = new Date().toISOString()

export const seedInstance: Instance = {
  id: MOCK_INSTANCE_ID,
  name: 'Mock Instance',
  type: 'development',
  onboarding_step: 'completed',
  subscription_plan: null,
  subscription_status: null,
  created_at: now,
  updated_at: now,
}

export const seedReceivers: Receiver[] = [
  {
    id: 're_mock_indiv01',
    type: 'individual',
    kyc_type: 'standard',
    kyc_status: 'approved',
    kyc_warnings: [],
    fraud_warnings: [],
    email: 'john.doe@example.com',
    tax_id: '536804398',
    address_line_1: '738 Plain St',
    address_line_2: null,
    city: 'Marshfield',
    state_province_region: 'MA',
    country: 'US',
    postal_code: '02050',
    ip_address: null,
    image_url: null,
    phone_number: '+13055555555',
    first_name: 'John',
    last_name: 'Doe',
    date_of_birth: '1990-01-15T00:00:00Z',
    legal_name: null,
    alternate_name: null,
    external_id: null,
    instance_id: MOCK_INSTANCE_ID,
    tos_id: null,
    owners: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: 're_mock_bizz01',
    type: 'business',
    kyc_type: 'standard',
    kyc_status: 'approved',
    kyc_warnings: [],
    fraud_warnings: [],
    email: 'finance@acmecorp.com',
    tax_id: '12345678000100',
    address_line_1: 'Av. Paulista 1000',
    address_line_2: 'Suite 200',
    city: 'Sao Paulo',
    state_province_region: 'SP',
    country: 'BR',
    postal_code: '01310-100',
    ip_address: null,
    image_url: null,
    phone_number: '+5511999999999',
    first_name: null,
    last_name: null,
    date_of_birth: null,
    legal_name: 'Acme Corp Ltda',
    alternate_name: 'Acme Corp',
    external_id: null,
    instance_id: MOCK_INSTANCE_ID,
    tos_id: null,
    owners: [],
    created_at: now,
    updated_at: now,
  },
]

export const seedBankAccounts: BankAccount[] = [
  {
    id: 'ba_mock_ach001',
    type: 'ach',
    name: 'John ACH Account',
    status: 'approved',
    recipient_relationship: 'first_party',
    pix_key: null,
    beneficiary_name: 'John Doe',
    routing_number: '021000021',
    account_number: '1234567890',
    account_type: 'checking',
    account_class: 'individual',
    address_line_1: '738 Plain St',
    address_line_2: null,
    city: 'Marshfield',
    state_province_region: 'MA',
    country: 'US',
    postal_code: '02050',
    spei_protocol: null, spei_clabe: null, spei_institution_code: null,
    transfers_type: null, transfers_account: null,
    ach_cop_beneficiary_first_name: null, ach_cop_beneficiary_last_name: null,
    ach_cop_document_id: null, ach_cop_document_type: null,
    ach_cop_email: null, ach_cop_bank_code: null, ach_cop_bank_account: null,
    swift_code_bic: null, swift_account_holder_name: null, swift_account_number_iban: null,
    swift_beneficiary_address_line_1: null, swift_beneficiary_address_line_2: null,
    swift_beneficiary_country: null, swift_beneficiary_city: null,
    swift_beneficiary_state_province_region: null, swift_beneficiary_postal_code: null,
    swift_bank_name: null, swift_bank_address_line_1: null, swift_bank_address_line_2: null,
    swift_bank_country: null, swift_bank_city: null,
    swift_bank_state_province_region: null, swift_bank_postal_code: null,
    swift_intermediary_bank_swift_code_bic: null, swift_intermediary_bank_account_number_iban: null,
    swift_intermediary_bank_name: null, swift_intermediary_bank_country: null,
    pix_safe_bank_code: null, pix_safe_branch_code: null, pix_safe_cpf_cnpj: null,
    tron_wallet_hash: null, swift_payment_code: null,
    receiver_id: 're_mock_indiv01',
    instance_id: MOCK_INSTANCE_ID,
    created_at: now, updated_at: now,
  },
  {
    id: 'ba_mock_pix001',
    type: 'pix',
    name: 'Acme PIX Account',
    status: 'approved',
    recipient_relationship: null,
    pix_key: '12345678000100',
    beneficiary_name: 'Acme Corp Ltda',
    routing_number: null, account_number: null,
    account_type: null, account_class: null,
    address_line_1: null, address_line_2: null, city: null,
    state_province_region: null, country: 'BR', postal_code: null,
    spei_protocol: null, spei_clabe: null, spei_institution_code: null,
    transfers_type: null, transfers_account: null,
    ach_cop_beneficiary_first_name: null, ach_cop_beneficiary_last_name: null,
    ach_cop_document_id: null, ach_cop_document_type: null,
    ach_cop_email: null, ach_cop_bank_code: null, ach_cop_bank_account: null,
    swift_code_bic: null, swift_account_holder_name: null, swift_account_number_iban: null,
    swift_beneficiary_address_line_1: null, swift_beneficiary_address_line_2: null,
    swift_beneficiary_country: null, swift_beneficiary_city: null,
    swift_beneficiary_state_province_region: null, swift_beneficiary_postal_code: null,
    swift_bank_name: null, swift_bank_address_line_1: null, swift_bank_address_line_2: null,
    swift_bank_country: null, swift_bank_city: null,
    swift_bank_state_province_region: null, swift_bank_postal_code: null,
    swift_intermediary_bank_swift_code_bic: null, swift_intermediary_bank_account_number_iban: null,
    swift_intermediary_bank_name: null, swift_intermediary_bank_country: null,
    pix_safe_bank_code: null, pix_safe_branch_code: null, pix_safe_cpf_cnpj: null,
    tron_wallet_hash: null, swift_payment_code: null,
    receiver_id: 're_mock_bizz01',
    instance_id: MOCK_INSTANCE_ID,
    created_at: now, updated_at: now,
  },
  {
    id: 'ba_mock_wire01',
    type: 'wire',
    name: 'John Wire Account',
    status: 'approved',
    recipient_relationship: 'first_party',
    pix_key: null,
    beneficiary_name: 'John Doe',
    routing_number: '021000021',
    account_number: '9876543210',
    account_type: 'checking',
    account_class: 'individual',
    address_line_1: '738 Plain St',
    address_line_2: null,
    city: 'Marshfield',
    state_province_region: 'MA',
    country: 'US',
    postal_code: '02050',
    spei_protocol: null, spei_clabe: null, spei_institution_code: null,
    transfers_type: null, transfers_account: null,
    ach_cop_beneficiary_first_name: null, ach_cop_beneficiary_last_name: null,
    ach_cop_document_id: null, ach_cop_document_type: null,
    ach_cop_email: null, ach_cop_bank_code: null, ach_cop_bank_account: null,
    swift_code_bic: null, swift_account_holder_name: null, swift_account_number_iban: null,
    swift_beneficiary_address_line_1: null, swift_beneficiary_address_line_2: null,
    swift_beneficiary_country: null, swift_beneficiary_city: null,
    swift_beneficiary_state_province_region: null, swift_beneficiary_postal_code: null,
    swift_bank_name: null, swift_bank_address_line_1: null, swift_bank_address_line_2: null,
    swift_bank_country: null, swift_bank_city: null,
    swift_bank_state_province_region: null, swift_bank_postal_code: null,
    swift_intermediary_bank_swift_code_bic: null, swift_intermediary_bank_account_number_iban: null,
    swift_intermediary_bank_name: null, swift_intermediary_bank_country: null,
    pix_safe_bank_code: null, pix_safe_branch_code: null, pix_safe_cpf_cnpj: null,
    tron_wallet_hash: null, swift_payment_code: null,
    receiver_id: 're_mock_indiv01',
    instance_id: MOCK_INSTANCE_ID,
    created_at: now, updated_at: now,
  },
  {
    id: 'ba_mock_swift1',
    type: 'international_swift',
    name: 'John SWIFT Account',
    status: 'approved',
    recipient_relationship: 'first_party',
    pix_key: null,
    beneficiary_name: null,
    routing_number: null, account_number: null,
    account_type: null, account_class: 'individual',
    address_line_1: null, address_line_2: null, city: null,
    state_province_region: null, country: null, postal_code: null,
    spei_protocol: null, spei_clabe: null, spei_institution_code: null,
    transfers_type: null, transfers_account: null,
    ach_cop_beneficiary_first_name: null, ach_cop_beneficiary_last_name: null,
    ach_cop_document_id: null, ach_cop_document_type: null,
    ach_cop_email: null, ach_cop_bank_code: null, ach_cop_bank_account: null,
    swift_code_bic: 'CHASUS33',
    swift_account_holder_name: 'John Doe',
    swift_account_number_iban: 'US12345678901234',
    swift_beneficiary_address_line_1: '738 PLAIN ST',
    swift_beneficiary_address_line_2: null,
    swift_beneficiary_country: 'US',
    swift_beneficiary_city: 'MARSHFIELD',
    swift_beneficiary_state_province_region: 'MA',
    swift_beneficiary_postal_code: '02050',
    swift_bank_name: 'JPMorgan Chase',
    swift_bank_address_line_1: '383 Madison Avenue',
    swift_bank_address_line_2: null,
    swift_bank_country: 'US',
    swift_bank_city: 'New York',
    swift_bank_state_province_region: 'NY',
    swift_bank_postal_code: '10179',
    swift_intermediary_bank_swift_code_bic: null,
    swift_intermediary_bank_account_number_iban: null,
    swift_intermediary_bank_name: null,
    swift_intermediary_bank_country: null,
    pix_safe_bank_code: null, pix_safe_branch_code: null, pix_safe_cpf_cnpj: null,
    tron_wallet_hash: null, swift_payment_code: null,
    receiver_id: 're_mock_indiv01',
    instance_id: MOCK_INSTANCE_ID,
    created_at: now, updated_at: now,
  },
]

export const seedBlockchainWallets: BlockchainWallet[] = [
  {
    id: 'bw_mock_evm001',
    address: '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
    network: 'base',
    is_account_abstraction: false,
    receiver_id: 're_mock_indiv01',
    instance_id: MOCK_INSTANCE_ID,
    external_id: null,
    created_at: now, updated_at: now,
  },
  {
    id: 'bw_mock_sol001',
    address: 'DRpbCBMxVnDK7maPH5a9Pub6ZjRKFWz7C4nHBmBGkGco',
    network: 'solana',
    is_account_abstraction: false,
    receiver_id: 're_mock_indiv01',
    instance_id: MOCK_INSTANCE_ID,
    external_id: null,
    created_at: now, updated_at: now,
  },
  {
    id: 'bw_mock_stl001',
    address: 'GBZXN7PIRZGNMHGA7MUUUF4GWPY5AYPV6LY4UV2GL6VJGIQRXFDNMADI',
    network: 'stellar',
    is_account_abstraction: false,
    receiver_id: 're_mock_bizz01',
    instance_id: MOCK_INSTANCE_ID,
    external_id: null,
    created_at: now, updated_at: now,
  },
]

export const seedApiKey: ApiKey = {
  id: 'ak_mock_key001',
  name: 'Mock API Key',
  key: 'bpk_test_mock_key_blindpay_cli',
  key_id: 'key_mock_001',
  permission: 'full_access',
  instance_id: MOCK_INSTANCE_ID,
  created_at: now,
  updated_at: now,
}
